/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExampleGet200Response
 */
export interface ExampleGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ExampleGet200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ExampleGet200Response interface.
 */
export function instanceOfExampleGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExampleGet200ResponseFromJSON(json: any): ExampleGet200Response {
    return ExampleGet200ResponseFromJSONTyped(json, false);
}

export function ExampleGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ExampleGet200ResponseToJSON(value?: ExampleGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

